---
name: Run all code checkers (style, static analysis, api versions etc.)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - uses: actions/setup-java@v4
        name: setup build jdk
        id: build_jdk
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: run code checkers
        env:
          MAVEN_ARGS: "-B -ff"
        run: |
          make install-notests

      - uses: actions/upload-artifact@v4
        name: upload build logs
        id: upload_build_logs
        continue-on-error: true
        if: ${{ always() }}
        with:
          name: build logs (${{ github.job }})
          retention-days: 90
          path: |
            **/target
            !**/target/**/*.jar
            !**/target/**/*.class

      - uses: actions/upload-artifact@v4
        name: upload build artifacts
        id: upload_build_artifacts
        continue-on-error: true
        with:
          name: build artifacts (${{ github.job }})
          retention-days: 1
          path: |
            **/target/**/*.jar


  reproducible-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - uses: actions/setup-java@v4
        name: setup build jdk
        id: build_jdk
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: run first build
        env:
          MAVEN_ARGS: "-B -ff"
        run: |
          make install-notests

      - name: compare builds
        env:
          MAVEN_ARGS: "-B -ff -Dbasepom.test.skip=true"
        run: |
          make compare-reproducible

      - uses: actions/upload-artifact@v4
        name: upload build logs
        id: upload_build_logs
        continue-on-error: true
        if: ${{ always() }}
        with:
          name: build logs (${{ github.job }})
          retention-days: 90
          path: |
            **/target
            !**/target/**/*.jar
            !**/target/**/*.class

      - uses: actions/upload-artifact@v4
        name: upload build artifacts
        id: upload_build_artifacts
        continue-on-error: true
        with:
          name: build artifacts (${{ github.job }})
          retention-days: 1
          path: |
            **/target/**/*.jar
